// Login Constants
export const CORPORATE_LOGIN_USER = "CORPORATE_LOGIN_USER";
export const CORPORATE_LOGIN_SUCCESS_USER = "CORPORATE_LOGIN_SUCCESS_USER";
export const CORPORATE_LOGIN_ERROR_USER = "CORPORATE_LOGIN_ERROR_USER";

// Logout Constants
export const CORPORATE_LOGOUT_USER = "CORPORATE_LOGOUT_USER";
export const CORPORATE_LOGOUT_SUCCESS_USER = "CORPORATE_LOGOUT_SUCCESS_USER";
export const CORPORATE_LOGOUT_ERROR_USER = "CORPORATE_LOGOUT_ERROR_USER";

// Registration Constants
export const CORPORATE_REGISTER_USER = "CORPORATE_REGISTER_USER";
export const CORPORATE_REGISTER_SUCCESS_USER = "CORPORATE_REGISTER_SUCCESS_USER";
export const CORPORATE_REGISTER_ERROR_USER = "CORPORATE_REGISTER_ERROR_USER";
