export const LOAD_PREFERENCES = "CORPORATE_LOAD_PREFERENCES";
export const LOAD_PREFERENCES_SUCCESS = "CORPORATE_LOAD_PREFERENCES_SUCCESS";
export const LOAD_PREFERENCES_ERROR = "CORPORATE_LOAD_PREFERENCES_ERROR";

export const LOAD_VISUALIZATIONS = "CORPORATE_LOAD_VISUALIZATIONS";
export const LOAD_VISUALIZATIONS_SUCCESS = "CORPORATE_LOAD_VISUALIZATIONS_SUCCESS";
export const LOAD_VISUALIZATIONS_ERROR = "CORPORATE_LOAD_VISUALIZATIONS_ERROR";

export const LOAD_COLOURS = "CORPORATE_LOAD_COLOURS";
export const LOAD_COLOURS_SUCCESS = "CORPORATE_LOAD_COLOURS_SUCCESS";
export const LOAD_COLOURS_ERROR = "CORPORATE_LOAD_COLOURS_ERROR";


export const CREATE_PREFERENCE = "CORPORATE_CREATE_PREFERENCE";
export const CREATE_PREFERENCE_SUCCESS = "CORPORATE_CREATE_PREFERENCE_SUCCESS";
export const CREATE_PREFERENCE_ERROR = "CORPORATE_CREATE_PREFERENCE_ERROR";

export const UPDATE_PREFERENCE = "CORPORATE_UPDATE_PREFERENCE";
export const UPDATE_PREFERENCE_SUCCESS = "CORPORATE_UPDATE_PREFERENCE_SUCCESS";
export const UPDATE_PREFERENCE_ERROR = "CORPORATE_UPDATE_PREFERENCE_ERROR";

export const REMOVE_PREFERENCE = "CORPORATE_REMOVE_PREFERENCE";
export const REMOVE_PREFERENCE_SUCCESS = "CORPORATE_REMOVE_PREFERENCE_SUCCESS";
export const REMOVE_PREFERENCE_ERROR = "CORPORATE_REMOVE_PREFERENCE_ERROR";