export const LOAD_PREFERENCES = "LOAD_PREFERENCES";
export const LOAD_PREFERENCES_SUCCESS = "LOAD_PREFERENCES_SUCCESS";
export const LOAD_PREFERENCES_ERROR = "LOAD_PREFERENCES_ERROR";

export const LOAD_VISUALIZATIONS = "LOAD_VISUALIZATIONS";
export const LOAD_VISUALIZATIONS_SUCCESS = "LOAD_VISUALIZATIONS_SUCCESS";
export const LOAD_VISUALIZATIONS_ERROR = "LOAD_VISUALIZATIONS_ERROR";

export const LOAD_COLOURS = "LOAD_COLOURS";
export const LOAD_COLOURS_SUCCESS = "LOAD_COLOURS_SUCCESS";
export const LOAD_COLOURS_ERROR = "LOAD_COLOURS_ERROR";


export const CREATE_PREFERENCE = "CREATE_PREFERENCE";
export const CREATE_PREFERENCE_SUCCESS = "CREATE_PREFERENCE_SUCCESS";
export const CREATE_PREFERENCE_ERROR = "CREATE_PREFERENCE_ERROR";

export const UPDATE_PREFERENCE = "UPDATE_PREFERENCE";
export const UPDATE_PREFERENCE_SUCCESS = "UPDATE_PREFERENCE_SUCCESS";
export const UPDATE_PREFERENCE_ERROR = "UPDATE_PREFERENCE_ERROR";

export const REMOVE_PREFERENCE = "REMOVE_PREFERENCE";
export const REMOVE_PREFERENCE_SUCCESS = "REMOVE_PREFERENCE_SUCCESS";
export const REMOVE_PREFERENCE_ERROR = "REMOVE_PREFERENCE_ERROR";