export const LOAD_ASSOCIATED_USERS = "LOAD_ASSOCIATED_USERS";
export const LOAD_ASSOCIATED_USERS_SUCCESS = "LOAD_ASSOCIATED_USERS_SUCCESS";
export const LOAD_ASSOCIATED_USERS_ERROR = "LOAD_ASSOCIATED_USERS_ERROR";

export const REMOVE_ASSOCIATED_USER = "REMOVE_ASSOCIATED_USER";
export const REMOVE_ASSOCIATED_USER_SUCCESS = "REMOVE_ASSOCIATED_USER_SUCCESS";
export const REMOVE_ASSOCIATED_USER_ERROR = "REMOVE_ASSOCIATED_USER_ERROR";
