// Login Constants
export const INDIVIDUAL_LOGIN_USER = "INDIVIDUAL_LOGIN_USER";
export const INDIVIDUAL_LOGIN_SUCCESS_USER = "INDIVIDUAL_LOGIN_SUCCESS_USER";
export const INDIVIDUAL_LOGIN_ERROR_USER = "INDIVIDUAL_LOGIN_ERROR_USER";

// Logout Constants
export const INDIVIDUAL_LOGOUT_USER = "INDIVIDUAL_LOGOUT_USER";
export const INDIVIDUAL_LOGOUT_SUCCESS_USER = "INDIVIDUAL_LOGOUT_SUCCESS_USER";
export const INDIVIDUAL_LOGOUT_ERROR_USER = "INDIVIDUAL_LOGOUT_ERROR_USER";

// Registration Constants
export const INDIVIDUAL_REGISTER_USER = "INDIVIDUAL_REGISTER_USER";
export const INDIVIDUAL_REGISTER_SUCCESS_USER = "INDIVIDUAL_REGISTER_SUCCESS_USER";
export const INDIVIDUAL_REGISTER_ERROR_USER = "INDIVIDUAL_REGISTER_ERROR_USER";
