export const LOAD_SETTINGS = "LOAD_SETTINGS";
export const LOAD_SETTINGS_SUCCESS = "LOAD_SETTINGS_SUCCESS";
export const LOAD_SETTINGS_ERROR = "LOAD_SETTINGS_ERROR";

export const ADD_ASSOCIATION = "ADD_ASSOCIATION";
export const ADD_ASSOCIATION_SUCCESS = "ADD_ASSOCIATION_SUCCESS";
export const ADD_ASSOCIATION_ERROR = "ADD_ASSOCIATION_ERROR";

export const REMOVE_ASSOCIATION = "REMOVE_ASSOCIATION";
export const REMOVE_ASSOCIATION_SUCCESS = "REMOVE_ASSOCIATION_SUCCESS";
export const REMOVE_ASSOCIATION_FAILURE = "REMOVE_ASSOCIATION_ERROR";